version: '3.8'

x-chat-signal-env: &chat-signal-env
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: 5672
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rabbit_chat
  EUREKA_URL: http://eureka:8761/eureka

x-mysql-credentials: &mysql-credentials
  MYSQL_USER: 'rchat_user'
  MYSQL_PASSWORD: 'password'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - "./.mysql-data/rabbit_chat:/var/lib/mysql"
    environment:
      <<: *mysql-credentials
      MYSQL_DATABASE: 'rabbit_chat'
      MYSQL_ROOT_PASSWORD: 'password'

  file-service:
    build: ../file-service
    restart: always
    ports:
      - '3001:3001'
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    volumes:
      - ./uploads-storage:/uploads-storage

  chat-signal-service00:
    build: ../chat-signal-service
    ports:
      - '3100:3100'
    environment:
      <<: *chat-signal-env
      <<: *mysql-credentials
      SERVER_PORT: 3100

  chat-signal-service01:
    build: ../chat-signal-service
    ports:
      - '3101:3101'
    environment:
      <<: *chat-signal-env
      <<: *mysql-credentials
      SERVER_PORT: 3101

  eureka:
    build: ../discovery-server
    restart: always
    ports:
      - '8761:8761'

  discovery-api:
    build: ../discovery-api
    restart: always
    ports:
      - '3002:3002'
    environment:
      EUREKA_URL: http://eureka:8761/eureka

  frontend:
    build: ../frontend
    restart: always
    ports:
      - '3000:3000'
