version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'rabbit_chat'
        MYSQL_USER: 'rchat_user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - "./.mysql-data/rabbit_chat:/var/lib/mysql"
