server.port: 3002

eureka:
  instance:
    appname: discovery-api
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
