spring:
  application:
    name: chat-signal-service
  datasource:
    url: jdbc:mysql://localhost:3306/rabbit_chat
    username: rchat_user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  sql:
    init:
      platform: mysql

eureka:
  instance:
    appname: chat-signal-service
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

logging:
  level:
    dev.zentari.chatnodeservice: debug
